FROM debian:stretch

RUN apt-get update && \
    apt-get install -y curl && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    echo 'source $HOME/.cargo/env' >> $HOME/.bashrc && \
    . $HOME/.cargo/env && \
    rustup target add i686-apple-darwin && \
    rustup target add x86_64-apple-darwin && \
    apt-get remove -y --purge curl && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
